Fix std::sleep behaviour with no tty terminal

diff --git a/potion b/potion
--- a/potion
+++ b/potion
@@ -1130,11 +1130,11 @@ link::absent () {
 file::_hmac () {
   ALGO="${ALGO:=sha1}"
   local hmac=
-  local path="$(os::path ${ALGO}sum)"
+  local path; path="$(os::path ${ALGO}sum)"
 
   if [ "$path" ]; then
     hmac="$(file::_data "$1" | ${ALGO}sum)"
-    read hmac _ <<<"${hmac}"
+    read -r hmac _ <<<"${hmac}"
     echo "$hmac"
   else
     err::trace "Required binary '${ALGO}sum' is not installed"
@@ -1174,12 +1174,13 @@ file::_data () {
 # opt: name: the filename to check for.
 # opt: data: the content URL
 file::exists () {
+  local data
   eval "$(std::parse "$@")"
 
   [ -r "$name" ] || return 1
 
-  local old_hmac="$(file::_hmac "file://$name")"
-  local new_hmac="$(file::_hmac "$data")"
+  local old_hmac; old_hmac="$(file::_hmac "file://$name")"
+  local new_hmac; new_hmac="$(file::_hmac "$data")"
   [ "$new_hmac" == "$old_hmac" ]
 }
 
@@ -1619,86 +1620,6 @@ mount::absent () {
     return 1
   fi
 }
-#!/bin/bash
-# mod: artifact
-# txt: The `artifact` module contains function to access to artifacts. An
-#      artifact is a file embedded in potion compiled object, usually you
-#      want to set some configuration files as artifacts.
-
-# fun: artifact::hmac <artifact_name>
-# txt: print to stdout the HMAC of the artifact passed as argument.
-# env: ALGO: set the algorithm to use for calculate HMAC. Valid values are:
-#      sha1, md5, sha256, sha512. The proper helper tool must be installed
-#      on the system.
-artifact::hmac () {
-  if artifact::exists "$1"; then
-    file::hmac "${BLIB_TMPDIR}/_artifacts/$1"
-  else
-    err::trace "Missing artifact while calculating HMAC: $1"
-  fi
-}
-
-# fun: artifact::extract
-# txt: extract artifacts if artifact support is enabled.
-artifact::extract () {
-  [ "$POTION_ARTIFACTS" ] || return 0
-  [ -e "${BLIB_TMPDIR}/.artifacts" ] && return 0
-
-  mutex::adquire _artifacts
-  tmp::create _artifacts
-  echo "${POTION_ARTIFACTS}" | base64 -d | tar x -C . ||
-    err::trace "Unable to extract artifacts"
-  touch "${BLIB_TMPDIR}/.artifacts"
-  tmp::exit
-  mutex::release _artifacts
-}
-
-# fun: artifact::exists <artifact_name>
-# txt: return true if the artifact exists, false otherwise.
-artifact::exists () {
-  artifact::extract
-  [ -r "${BLIB_TMPDIR}/_artifacts/$1" ]
-}
-
-# fun: artifact::read <artifact_name>
-# txt: read a specific artifact from potion.
-artifact::read () {
-  artifact::exists "$1" ||
-    err::trace "Missing artifact: '$1'"
-
-  cat "${BLIB_TMPDIR}/_artifacts/$1"
-}
-
-
-# fun: artifact::eval <artifact_name>
-# txt: read and eval specific artifact from potion.
-artifact::eval () {
-  artifact::exists "$1" ||
-    err::trace "Missing artifact: '$1'"
-
-  local content
-
-  content="$(< "${BLIB_TMPDIR}/_artifacts/$1")"
-  eval echo -n \""${content//\"/\\\"}"\"
-}
-
-# fun: artifact::build <directory>
-# txt: scan the directory passed as argument and return a POTION_ARTIFACTS
-#      variable to stdout with the encoded version of the artifacts.
-artifact::build () {
-  local artifacts
-  artifacts="$(cd "$1" && tar -c . | base64 -w0)"
-  echo "POTION_ARTIFACTS='${artifacts}'"
-  echo
-}
-
-# fun: artifact::load <directory>
-# txt: load in environment potion artifacts
-artifact::load ()
-{
-  eval "$(artifact::build "${1}")"
-  out::user "dumped artifacts from: ${1}"
-}
 #! /bin/bash
 # mod: debug
 # api: blib
@@ -1844,7 +1765,7 @@ mutex::adquire () {
   while ! std::mute mkdir "_mutex_$1"; do
     [ $i -eq ${MUTEX_TIMEOUT:-3600} ] && err::trace "Mutex timeout: $1"
     ${VERBOSE:-false} && out::user "waiting for mutex: $1 ($_run)"
-    std::sleep 1
+    sleep 1
     ((i++))
   done
   tmp::exit
@@ -2575,7 +2496,87 @@ tmp::file () {
 tmp::touch () {
   mkdir -p "${BLIB_TMPDIR}" && : > "${BLIB_TMPDIR}/$1"
 }
-BLIB_VERSION='1.0.1'
+BLIB_VERSION='1.0.2'
+#!/bin/bash
+# mod: artifact
+# txt: The `artifact` module contains function to access to artifacts. An
+#      artifact is a file embedded in potion compiled object, usually you
+#      want to set some configuration files as artifacts.
+
+# fun: artifact::hmac <artifact_name>
+# txt: print to stdout the HMAC of the artifact passed as argument.
+# env: ALGO: set the algorithm to use for calculate HMAC. Valid values are:
+#      sha1, md5, sha256, sha512. The proper helper tool must be installed
+#      on the system.
+artifact::hmac () {
+  if artifact::exists "$1"; then
+    file::hmac "${BLIB_TMPDIR}/_artifacts/$1"
+  else
+    err::trace "Missing artifact while calculating HMAC: $1"
+  fi
+}
+
+# fun: artifact::extract
+# txt: extract artifacts if artifact support is enabled.
+artifact::extract () {
+  [ "$POTION_ARTIFACTS" ] || return 0
+  [ -e "${BLIB_TMPDIR}/.artifacts" ] && return 0
+
+  mutex::adquire _artifacts
+  tmp::create _artifacts
+  echo "${POTION_ARTIFACTS}" | base64 -d | tar x -C . ||
+    err::trace "Unable to extract artifacts"
+  touch "${BLIB_TMPDIR}/.artifacts"
+  tmp::exit
+  mutex::release _artifacts
+}
+
+# fun: artifact::exists <artifact_name>
+# txt: return true if the artifact exists, false otherwise.
+artifact::exists () {
+  artifact::extract
+  [ -r "${BLIB_TMPDIR}/_artifacts/$1" ]
+}
+
+# fun: artifact::read <artifact_name>
+# txt: read a specific artifact from potion.
+artifact::read () {
+  artifact::exists "$1" ||
+    err::trace "Missing artifact: '$1'"
+
+  cat "${BLIB_TMPDIR}/_artifacts/$1"
+}
+
+
+# fun: artifact::eval <artifact_name>
+# txt: read and eval specific artifact from potion.
+artifact::eval () {
+  artifact::exists "$1" ||
+    err::trace "Missing artifact: '$1'"
+
+  local content
+
+  content="$(< "${BLIB_TMPDIR}/_artifacts/$1")"
+  eval echo -n \""${content//\"/\\\"}"\"
+}
+
+# fun: artifact::build <directory>
+# txt: scan the directory passed as argument and return a POTION_ARTIFACTS
+#      variable to stdout with the encoded version of the artifacts.
+artifact::build () {
+  local artifacts
+  artifacts="$(cd "$1" && tar -c . | base64 -w0)"
+  echo "POTION_ARTIFACTS='${artifacts}'"
+  echo
+}
+
+# fun: artifact::load <directory>
+# txt: load in environment potion artifacts
+artifact::load ()
+{
+  eval "$(artifact::build "${1}")"
+  out::user "dumped artifacts from: ${1}"
+}
 #! /bin/bash
 # mod: main
 # txt: The ``main`` module contain the specified potion body.
