doc: fix examples with wrong escape sequences
Signed-off-by: Andrés J. Díaz <ajdiaz@ajdiaz.me>

diff --git a/potion b/potion
--- a/potion
+++ b/potion
@@ -1000,199 +1000,6 @@ dir::exists () {
   [ -d "$name" ]
 }
 #! /bin/bash
-# mod: file
-# api: External
-# txt: The `file` module provides functions to ensure that specified file
-#      exists or not in the system and also has specified content.
-#      To creat content, use the ``content`` parameter, usually this parameter
-#      accepts a URL (in the usual curl accepted format or ``artifact://``
-#      to read from static artifact or ``artifact+eval://`` to read from an
-#      evaluated artifact.
-#
-# use: file::present /etc/somefile \\
-#        content="artifact://someartifact"
-# use: file::present /etc/otherfile \\
-#        content="some string content"
-
-# private file::hmac <url>
-file::_hmac () {
-  ALGO="${ALGO:=sha1}"
-  local hmac=
-  local path; path="$(os::path ${ALGO}sum)"
-
-  if [ "$path" ]; then
-    hmac="$(file::_data "$1" | ${ALGO}sum)"
-    read -r hmac _ <<<"${hmac}"
-    echo "$hmac"
-  else
-    err::trace "Required binary '${ALGO}sum' is not installed"
-  fi
-}
-
-# private file::_data <url>
-file::_data () {
-  case "$1" in
-    artifact://*) 
-      local name="${1##artifact://}"
-      artifact::exists "${name}" ||
-        err::trace "Missing artifact: $1"
-      artifact::read "$name"
-      ;;
-    artifact+eval://*)
-      local name="${1##artifact+eval://}"
-      artifact::exists "${name}" ||
-        err::trace "Missing artifact: $1"
-      artifact::eval "$name"
-      ;;
-    http://*|https://*|ftp://*)
-      curl::get "$1"
-      ;;
-    file://*)
-      cat "${1#file://}"
-      ;;
-    *)
-      echo "$1"
-      ;;
-  esac
-}
-
-# fun: file::exists [name=]<fname> [options]
-# api: External
-# txt: return true if file exists, or none otherwise
-# opt: name: the filename to check for.
-# opt: content: the content URL
-file::exists () {
-  local content
-  eval "$(std::parse "$@")"
-
-  [ -r "$name" ] || return 1
-
-  local old_hmac; old_hmac="$(file::_hmac "file://$name")"
-  local new_hmac; new_hmac="$(file::_hmac "$content")"
-  if [[ "$new_hmac" == "$old_hmac" ]]; then
-    return 0
-  elif ${SHOWDIFF:-false}; then
-    # shellcheck disable=SC2086
-    echo "$content" | diff ${DIFF_OPTIONS:--Naurr --color=always} "$name" -
-  fi
-  return 1
-}
-
-# private file::create <fname> <owner:group> <mode> <content>
-file::_create () {
-  # we required an explitic if here because of the redirection.
-  if ! ${PRETEND:-false}; then
-    file::_data "$4" > "$1" ||
-      err::trace "Unable to dump content to file: $1"
-  fi
-
-  # shellcheck disable=SC2015
-  std::run chown "${2:-0:0}" "$1" &&
-    std::run chmod "${3:-644}" "$1" ||
-    err::trace "Unable to set permissions to file: $1"
-}
-
-# private file::destroy <fname>
-file::_destroy () {
-  std::run rm -f "$1"
-}
-
-# private file::_mode <fname>
-file::_mode ()
-{
-  stat -c '%#a' "$1"
-}
-
-# private file::_owner <fname>
-file::_owner ()
-{
-  stat -c '%U' "$1"
-}
-
-# private file::_group <fname>
-file::_group ()
-{
-  stat -c '%G' "$1"
-}
-
-# fun: file::present [name=]<name> [options]
-# api: External
-# txt: ensure that file passed as argument exists.
-# opt: name: then file name to ensure
-# opt: user: the user owner the file
-# opt: group: the group owner the file
-# opt: mode: the four digit octal mode of the file (i.e. 0644)
-# opt: content: the content url
-file::present () {
-  eval "$(std::parse "$@")"
-  local group="${group:-$LOGNAME}"
-  local user="${user:-$LOGNAME}"
-
-  # Deprecation check
-  local data
-  if [[ "$data" ]] && [[ ! "$content" ]]; then
-    local content="$data"
-    deprecated data \
-      version=1.0 \
-      message="'data' parameter in file is deprecated, use 'content' instead"
-  fi
-
-  if ! file::exists "$name" "content=$content"; then
-    if file::_create "$name" "${user}:${group}" "${mode:-0644}" "$content"
-    then
-      res::created file \
-        "name=$name user=${user} group=${group} mode=${mode:-0644}"
-    else
-      err::trace "Unable to create file: $name"
-    fi
-  else
-    local ret=1
-    if [[ "$(file::_mode "$name")" -ne "${mode:-0644}" ]]; then
-      if std::run chmod "${mode:-0644}" "$name"; then
-        res::created file "name=$name mode=${mode:-0644}"
-        ret=0
-      else
-        err::trace "Unable to re-set permissions to file: $name"
-      fi
-    fi
-
-    if [[ "$(file::_owner "$name")" != "${user}" ]]; then
-      if std::run chown "${user}" "$name"; then
-        res::created file "name=$name user=${user}"
-        ret=0
-      else
-        err::trace "Unable to re-set owner to file: $name"
-      fi
-    fi
-
-    if [[ "$(file::_group "$name")" != "${group}" ]]; then
-      if std::run chgrp "${group}" "$name"; then
-        res::created file "name=$name group=${group}"
-        ret=0
-      else
-        err::trace "Unable to re-set group to file: $name"
-      fi
-    fi
-
-    return "$ret"
-  fi
-}
-
-# fun: file::absent [name=]<name> [options]
-# api: External
-# txt: ensure that file passed as argument does not exist.
-# opt: content: the content url (only removes the file if content is the same).
-file::absent () {
-  eval "$(std::parse "$@")"
-  if file::exists "$name" "content=$content"; then
-    file::_destroy "$name" &&
-      res::deleted file "name=$name" ||
-      err::trace "Unable to destroy file: $name"
-  else
-    return 1
-  fi
-}
-#! /bin/bash
 # mod: format
 # api: External
 # txt: The `format` module provides a way to format and mount specified
@@ -1254,88 +1061,6 @@ format::absent () {
   out::warn "To avoid data loss format::absent do nothing for device $*"
 }
 
-#! /bin/bash
-# vim: ft=sh:
-# mod: fstab
-# txt: The `fstab` module provides functions to add entries to fstab file.
-# use: fstab::present /dev/sda1 \\
-#        mount=/ \\
-#        fstype=xfs \\
-#        opts=default,noauto \\
-#        remount=true
-
-# fun: fstab::exists [name=]<device>
-# api: External
-# txt: return true if device is set in fstab
-fstab::exists () {
-  local name
-  eval "$(std::parse "$@")"
-  std::mute grep -q "^$name" /etc/fstab
-}
-
-# private fstab::_create <device> <mntpoint> <type> [options] [dump] [pass]
-fstab::_create () {
-  local mount
-  eval "$(std::parse "$@")"
-  [ "$mount" ] || err::trace "fstab require mount parameter"
-  ${PRETEND:-false} || 
-    echo "$name $mount ${fstype:-auto} ${opts:-defaults}" \
-         "${dump:-1} ${pass:-2}" >> /etc/fstab
-
-  if ${FSTAB_REMOUNT:-false}; then
-    std::run mount "-oremount,${opts}" "$mount"
-  fi
-
-  if ${FSTAB_MOUNT:-false}; then
-    std::run mount "$mount"
-  fi
-}
-
-# private fstab::_destroy <device>
-fstab::_destroy () {
-  local fstab
-  fstab="$(grep -v "^$1" /etc/fstab)"
-  ${PRETEND:-false} || echo "$fstab" > /etc/fstab
-}
-
-# fun: fstab::present [name=]<device> mount=<mountpoint> [options]
-# api: External
-# txt: ensure that fstab entry for device is present
-# opt: name: the device name to ensure
-# opt: mount: the mountpoint for the device
-# opt: fstype: the fstype of the device filesystem (default: auto)
-# opt: opts: mount options (default: defaults)
-# opt: dump: the dump number (default 0)
-# opt: pass: the pass number (default 1)
-# opt: remount: if true remount device when added to fstab
-fstab::present () {
-  local remount
-  if ! fstab::exists "$@"; then
-    # shellcheck disable=SC2015
-    FSTAB_REMOUNT="$remount" \
-      fstab::_create "$@" &&
-        res::created fstab "$@" ||
-        err::trace "Unable to create fstab for device: $*"
-  else
-    return 1
-  fi
-}
-
-# fun: fstab::absent [name=]<device>
-# api: External
-# txt: ensure that specified device has not entry in fstab
-fstab::absent () {
-  eval "$(std::parse "$@")"
-  if fstab::exists "$name"; then
-    if fstab::_destroy "$name"; then
-      res::deleted fstab "device=$name"
-    else
-      err::trace "Unable to destroy fstab for device: $1"
-    fi
-  else
-    return 1
-  fi
-}
 #! /bin/bash
 # mod: group
 # api: External
@@ -2297,14 +2022,207 @@ tz::absent () {
   fi
 }
 #! /bin/bash
+# mod: file
+# api: External
+# txt: The `file` module provides functions to ensure that specified file
+#      exists or not in the system and also has specified content.
+#      To creat content, use the ``content`` parameter, usually this parameter
+#      accepts a URL (in the usual curl accepted format or ``artifact://``
+#      to read from static artifact or ``artifact+eval://`` to read from an
+#      evaluated artifact.
+#
+# use: file::present /etc/somefile \
+#        content="artifact://someartifact"
+# use: file::present /etc/otherfile \
+#        content="some string content"
+
+# private file::hmac <url>
+file::_hmac () {
+  ALGO="${ALGO:=sha1}"
+  local hmac=
+  local path; path="$(os::path ${ALGO}sum)"
+
+  if [ "$path" ]; then
+    hmac="$(file::_data "$1" | ${ALGO}sum)"
+    read -r hmac _ <<<"${hmac}"
+    echo "$hmac"
+  else
+    err::trace "Required binary '${ALGO}sum' is not installed"
+  fi
+}
+
+# private file::_data <url>
+file::_data () {
+  case "$1" in
+    artifact://*) 
+      local name="${1##artifact://}"
+      artifact::exists "${name}" ||
+        err::trace "Missing artifact: $1"
+      artifact::read "$name"
+      ;;
+    artifact+eval://*)
+      local name="${1##artifact+eval://}"
+      artifact::exists "${name}" ||
+        err::trace "Missing artifact: $1"
+      artifact::eval "$name"
+      ;;
+    http://*|https://*|ftp://*)
+      curl::get "$1"
+      ;;
+    file://*)
+      cat "${1#file://}"
+      ;;
+    *)
+      echo "$1"
+      ;;
+  esac
+}
+
+# fun: file::exists [name=]<fname> [options]
+# api: External
+# txt: return true if file exists, or none otherwise
+# opt: name: the filename to check for.
+# opt: content: the content URL
+file::exists () {
+  local content
+  eval "$(std::parse "$@")"
+
+  [ -r "$name" ] || return 1
+
+  local old_hmac; old_hmac="$(file::_hmac "file://$name")"
+  local new_hmac; new_hmac="$(file::_hmac "$content")"
+  if [[ "$new_hmac" == "$old_hmac" ]]; then
+    return 0
+  elif ${SHOWDIFF:-false}; then
+    # shellcheck disable=SC2086
+    echo "$content" | diff ${DIFF_OPTIONS:--Naurr --color=always} "$name" -
+  fi
+  return 1
+}
+
+# private file::create <fname> <owner:group> <mode> <content>
+file::_create () {
+  # we required an explitic if here because of the redirection.
+  if ! ${PRETEND:-false}; then
+    file::_data "$4" > "$1" ||
+      err::trace "Unable to dump content to file: $1"
+  fi
+
+  # shellcheck disable=SC2015
+  std::run chown "${2:-0:0}" "$1" &&
+    std::run chmod "${3:-644}" "$1" ||
+    err::trace "Unable to set permissions to file: $1"
+}
+
+# private file::destroy <fname>
+file::_destroy () {
+  std::run rm -f "$1"
+}
+
+# private file::_mode <fname>
+file::_mode ()
+{
+  stat -c '%#a' "$1"
+}
+
+# private file::_owner <fname>
+file::_owner ()
+{
+  stat -c '%U' "$1"
+}
+
+# private file::_group <fname>
+file::_group ()
+{
+  stat -c '%G' "$1"
+}
+
+# fun: file::present [name=]<name> [options]
+# api: External
+# txt: ensure that file passed as argument exists.
+# opt: name: then file name to ensure
+# opt: user: the user owner the file
+# opt: group: the group owner the file
+# opt: mode: the four digit octal mode of the file (i.e. 0644)
+# opt: content: the content url
+file::present () {
+  eval "$(std::parse "$@")"
+  local group="${group:-$LOGNAME}"
+  local user="${user:-$LOGNAME}"
+
+  # Deprecation check
+  local data
+  if [[ "$data" ]] && [[ ! "$content" ]]; then
+    local content="$data"
+    deprecated data \
+      version=1.0 \
+      message="'data' parameter in file is deprecated, use 'content' instead"
+  fi
+
+  if ! file::exists "$name" "content=$content"; then
+    if file::_create "$name" "${user}:${group}" "${mode:-0644}" "$content"
+    then
+      res::created file \
+        "name=$name user=${user} group=${group} mode=${mode:-0644}"
+    else
+      err::trace "Unable to create file: $name"
+    fi
+  else
+    local ret=1
+    if [[ "$(file::_mode "$name")" -ne "${mode:-0644}" ]]; then
+      if std::run chmod "${mode:-0644}" "$name"; then
+        res::created file "name=$name mode=${mode:-0644}"
+        ret=0
+      else
+        err::trace "Unable to re-set permissions to file: $name"
+      fi
+    fi
+
+    if [[ "$(file::_owner "$name")" != "${user}" ]]; then
+      if std::run chown "${user}" "$name"; then
+        res::created file "name=$name user=${user}"
+        ret=0
+      else
+        err::trace "Unable to re-set owner to file: $name"
+      fi
+    fi
+
+    if [[ "$(file::_group "$name")" != "${group}" ]]; then
+      if std::run chgrp "${group}" "$name"; then
+        res::created file "name=$name group=${group}"
+        ret=0
+      else
+        err::trace "Unable to re-set group to file: $name"
+      fi
+    fi
+
+    return "$ret"
+  fi
+}
+
+# fun: file::absent [name=]<name> [options]
+# api: External
+# txt: ensure that file passed as argument does not exist.
+# opt: content: the content url (only removes the file if content is the same).
+file::absent () {
+  eval "$(std::parse "$@")"
+  if file::exists "$name" "content=$content"; then
+    file::_destroy "$name" &&
+      res::deleted file "name=$name" ||
+      err::trace "Unable to destroy file: $name"
+  else
+    return 1
+  fi
+}
+#! /bin/bash
 # mod: user
 # api: External
 # txt: The `user` module provides functions to manage users in the system.
 # use: group::present mygroup
-#      user::present someuser \\
-#        groups=adm,mygroup \\
-#        nohome=true \\
-#        system=true \\
+#      user::present someuser \
+#        groups=adm,mygroup \
+#        nohome=true \
+#        system=true \
 #        shel=/bin/false
 
 # fun: user::exists [name=]<username>
@@ -2404,6 +2322,88 @@ user::absent () {
     user::_destroy "$name" &&
       res::deleted user "$name" ||
       err::trace "unable to destroy user $name"
+  else
+    return 1
+  fi
+}
+#! /bin/bash
+# vim: ft=sh:
+# mod: fstab
+# txt: The `fstab` module provides functions to add entries to fstab file.
+# use: fstab::present /dev/sda1 \
+#        mount=/ \
+#        fstype=xfs \
+#        opts=default,noauto \
+#        remount=true
+
+# fun: fstab::exists [name=]<device>
+# api: External
+# txt: return true if device is set in fstab
+fstab::exists () {
+  local name
+  eval "$(std::parse "$@")"
+  std::mute grep -q "^$name" /etc/fstab
+}
+
+# private fstab::_create <device> <mntpoint> <type> [options] [dump] [pass]
+fstab::_create () {
+  local mount
+  eval "$(std::parse "$@")"
+  [ "$mount" ] || err::trace "fstab require mount parameter"
+  ${PRETEND:-false} || 
+    echo "$name $mount ${fstype:-auto} ${opts:-defaults}" \
+         "${dump:-1} ${pass:-2}" >> /etc/fstab
+
+  if ${FSTAB_REMOUNT:-false}; then
+    std::run mount "-oremount,${opts}" "$mount"
+  fi
+
+  if ${FSTAB_MOUNT:-false}; then
+    std::run mount "$mount"
+  fi
+}
+
+# private fstab::_destroy <device>
+fstab::_destroy () {
+  local fstab
+  fstab="$(grep -v "^$1" /etc/fstab)"
+  ${PRETEND:-false} || echo "$fstab" > /etc/fstab
+}
+
+# fun: fstab::present [name=]<device> mount=<mountpoint> [options]
+# api: External
+# txt: ensure that fstab entry for device is present
+# opt: name: the device name to ensure
+# opt: mount: the mountpoint for the device
+# opt: fstype: the fstype of the device filesystem (default: auto)
+# opt: opts: mount options (default: defaults)
+# opt: dump: the dump number (default 0)
+# opt: pass: the pass number (default 1)
+# opt: remount: if true remount device when added to fstab
+fstab::present () {
+  local remount
+  if ! fstab::exists "$@"; then
+    # shellcheck disable=SC2015
+    FSTAB_REMOUNT="$remount" \
+      fstab::_create "$@" &&
+        res::created fstab "$@" ||
+        err::trace "Unable to create fstab for device: $*"
+  else
+    return 1
+  fi
+}
+
+# fun: fstab::absent [name=]<device>
+# api: External
+# txt: ensure that specified device has not entry in fstab
+fstab::absent () {
+  eval "$(std::parse "$@")"
+  if fstab::exists "$name"; then
+    if fstab::_destroy "$name"; then
+      res::deleted fstab "device=$name"
+    else
+      err::trace "Unable to destroy fstab for device: $1"
+    fi
   else
     return 1
   fi
