Add support for remote repository run

diff --git a/potion b/potion
--- a/potion
+++ b/potion
@@ -120,9 +120,29 @@ context::run () {
 # txt: The `include` module allows you to include other potions from remote
 #      sites.
 
+# fun: include <url>
+# api: potion
+# txt: include a potion from URL, git repo or file.
 include ()
 {
-  curl::source "$1"
+  local url=
+  case "$1" in
+    git://*|ssh+git://*)
+      url="${1/ssh+git:/ssh:}"
+      tmp::create origin
+      out::info $"Cloning remote potion spells from: ${url}..."
+      std::mute git clone --depth 1 "$url" . ||
+        err::trace $"Unable to clone repository: $url"
+      [[ -r ./init.potion ]] ||
+        err::trace $"Cloned repository does not provide init.potion file"
+      curl::source ./init.potion ||
+        err::trace $"Unable to load init.potion file"
+      tmp::exit
+      ;;
+    *)
+      curl::source "$1"
+      ;;
+  esac
 }
 #! /bin/bash
 # mod: host
@@ -1541,7 +1561,7 @@ artifact::eval () {
   eval echo -n \""${content//\"/\\\"}"\"
 }
 
-# fun: artifacts::build <directory>
+# fun: artifact::build <directory>
 # txt: scan the directory passed as argument and return a POTION_ARTIFACTS
 #      variable to stdout with the encoded version of the artifacts.
 artifact::build () {
@@ -1549,6 +1569,14 @@ artifact::build () {
   artifacts="$(cd "$1" && tar -c . | base64 -w0)"
   echo "POTION_ARTIFACTS='${artifacts}'"
   echo
+}
+
+# fun: artifact::load <directory>
+# txt: load in environment potion artifacts
+artifact::load ()
+{
+  eval "$(artifact::build "${1}")"
+  out::user "dumped artifacts from: ${1}"
 }
 #! /bin/bash
 # mod: debug
@@ -2537,7 +2565,7 @@ main::run () {
     out::user "loaded secrets from: ${main__run__secrets}"
   fi
   for src in "$@"; do
-    curl::source "$src" || err::trace "Unable to load potion file(s): $src"
+    include "$src" || err::trace "Unable to load potion file(s): $src"
   done
   context::run
 }
diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -108,7 +108,7 @@ main::run () {
     out::user "loaded secrets from: ${main__run__secrets}"
   fi
   for src in "$@"; do
-    curl::source "$src" || err::trace "Unable to load potion file(s): $src"
+    include "$src" || err::trace "Unable to load potion file(s): $src"
   done
   context::run
 }
