Use stderr catch in contexts

diff --git a/potion b/potion
--- a/potion
+++ b/potion
@@ -117,6 +117,7 @@ context::execute () {
 
 # fun: context::run
 # txt: run all context in paralell.
+declare -a context__run__pids=()
 context::run () {
   local tim cctx=0
 
@@ -135,9 +136,15 @@ context::run () {
 
   while read -r _ _ context; do
     context::execute "$context" &
-    ${ONETHREAD:-false} && wait
+    if ${ONETHREAD:-false}; then
+      wait $!
+    else
+      context__run__pids+=( "$!" )
+    fi
   done < <(declare -F | grep '^declare -f @')
-  wait
+  if ! ${ONETHREAD:-false}; then
+    wait "${context__run__pids[@]}"
+  fi
   context::task::apply "main"
   tim="$(( $(std::timestamp) - tim ))"
   out::info "Finished potion exection in ${tim} seconds."
@@ -319,7 +326,13 @@ file::exists () {
 
   local old_hmac; old_hmac="$(file::_hmac "file://$name")"
   local new_hmac; new_hmac="$(file::_hmac "$data")"
-  [ "$new_hmac" == "$old_hmac" ]
+  if [[ "$new_hmac" == "$old_hmac" ]]; then
+    return 0
+  elif ${SHOWDIFF:-false}; then
+    # shellcheck disable=SC2086
+    echo "$data" | diff ${DIFF_OPTIONS:--Naurr --color=always} "$name" -
+  fi
+  return 1
 }
 
 # private file::create <fname> <owner:group> <mode> <data>
@@ -330,6 +343,7 @@ file::_create () {
       err::trace "Unable to dump content to file: $1"
   fi
 
+  # shellcheck disable=SC2015
   std::run chown "${2:-0:0}" "$1" &&
     std::run chmod "${3:-644}" "$1" ||
     err::trace "Unable to set permissions to file: $1"
@@ -1748,28 +1762,91 @@ res::refreshed () {
 # env: SECRET_MASTERKEY: Path to file where the master key for secrets lives.
 #      By default ``/etc/potion.key``
 
-SECRET_MASTERKEY=/etc/potion.key
+SECRET_MASTERKEY="${SECRET_MASTERKEY:-/etc/potion.key}"
 
 declare -A _secrets
 
-# fun: secret::load [name=]<name>
-# txt: load a secret file
-secret::load () {
+# fun: secret::dump [name=]<name>
+# txt: dump the encrypted file of a secret plain file.
+secret::dump ()
+{
+  _gpg () {
+    gpg --symmetric -z 9 --require-secmem \
+        --cipher-algo AES256 --s2k-cipher-algo AES256 \
+        --s2k-digest-algo SHA512 --s2k-mode 3 --batch \
+        --s2k-count 65000000 --compress-algo BZIP2 --armor \
+        --passphrase-file "${SECRET_MASTERKEY}"
+  }
+
   local url="${1#name=}"
   case "$url" in
     gpg://*|gpg+file://*)
       url="${url#*://}"
-      eval "$(gpg -d "$url")";;
+      _gpg < "$url";;
     gpg+*)
       url="${url#gpg+}"
-      eval "$(curl -sqL "$url" | gpg -d)";;
+      curl -sqL "$url" | _gpg;;
+    crypt+*)
+      url="${url#crypt+}"
+      curl -sqL "$url" |
+              openssl enc -e -a -aes-256-cbc -kfile "${SECRET_MASTERKEY}";;
+    *) url="${url#file://}"
+       # shellcheck disable=SC1090
+       cat "$url" || err::trace "Invalid secret file format" ;;
+  esac
+}
+
+# fun: secret::load [name=]<name>
+# txt: load a secret file
+secret::load () {
+  local err=$"Unable to load secrets"
+  local url="${1#name=}"
+  case "$url" in
+    gpg://*|gpg+file://*)
+      url="${url#*://}"
+      eval "$(gpg -d --batch --passphrase-file "$SECRET_MASTERKEY" "$url")" ||
+        err::trace "$err"
+      ;;
+    gpg+*)
+      url="${url#gpg+}"
+      eval "$(curl -sqL "$url" |
+              gpg -d --batch --passphrase-file "$SECRET_MASTERKEY")" ||
+                err::trace "$err"
+      ;;
     crypt+*)
       url="${url#crypt+}"
       eval "$(curl -sqL "$url" |
-              openssl enc -d -a -aes256 -kfile "${SECRET_MASTERKEY}")";;
+              openssl enc -d -a -aes-256-cbc -kfile "${SECRET_MASTERKEY}")" ||
+        err::trace "$err"
+      ;;
     *) url="${url#file://}"
        # shellcheck disable=SC1090
-       source "$url" || err::trace "Invalid secret file format" ;;
+       source "$url" || err::trace "$err" ;;
+  esac
+}
+
+# fun: secret::load_inline <format> <content>
+# txt: load scripts from the inline string. Available formats are plain,
+#      crypt or gpg.
+secret::load_inline () {
+  local err=$"Unable to load secrets inline"
+  local format="${1#name=}"
+  case "$format" in
+    gpg)
+      eval "$(gpg --batch --passphrase-file "${SECRET_MASTERKEY}" -d <<<"$2")" ||
+        err::trace "$err"
+      ;;
+    crypt)
+      eval "$(openssl enc -d -a -aes-256-cbc -kfile "${SECRET_MASTERKEY}" <<<"$2")" ||
+        err::trace "$err"
+      ;;
+    plain)
+      eval "$2" || err::trace "$err"
+      ;;
+    *)
+      # shellcheck disable=SC1090
+      source "$url" || err::trace "$err"
+      ;;
   esac
 }
 
@@ -1786,6 +1863,47 @@ secret::add () {
 # txt: return the secret text associated with specified name
 secret () {
   echo "${_secrets["$1"]}"
+}
+#! /bin/bash
+# mod: deprecate
+# txt: This internal module provides a way to mark deprecated features or
+#      modules.
+
+# fun: deprecate [name=]<name> [version=version] [date=date]
+# txt: set a deprecation mark called name (could be a message), when potion
+#      version is lower to specified version a warning is raised, otherwise
+#      execution fails with an error. The same behaviour can be used with
+#      a date in the format %y-%m-%d, until that date the deprecation
+#      warning message will show, after that date execution breaks.
+deprecate () {
+  local version date name
+  eval "$(std::parse "$@")"
+
+  # shellcheck disable=SC2153
+  version::cmp "$VERSION" "$version"
+  case $? in
+    0|255)
+      err::trace "DEPRECATION ERROR: $name";;
+    1)
+      local line fun file; read -r line fun file < <(caller)
+      out::warn $"DEPRECATION WARNING [$fun at $file:$line]: $name"
+  esac
+
+  [[ "$date" ]] || return
+
+  local year month day
+
+  { IFS='-' read -r year month day <<< "$date"; }
+
+  if [[ "$year" -lt "$(printf "%(%Y)T" -1)" ]] &&
+    [[ "$month" -lt "$(printf "%(%m)T" -1)" ]] &&
+    [[ "$day" -lt "$(printf "%(%d)T" -1)" ]]
+  then
+      local line fun file; read -r line fun file < <(caller)
+      out::warn $"DEPRECATION WARNING [$fun at $file:$line]: $name"
+  else
+    err::trace "DEPRECATION ERROR: $name"
+  fi
 }
 #! /bin/bash
 # mod: arg
@@ -2195,11 +2313,11 @@ ${DEBUG:+set -x}
 # txt: print to stderr a traceback of an error.
 # use: false || err::trace "Error because of false"
 err::trace () {
-  echo "${COLOR_FAIL}Traceback (most recent call last):${COLOR_NONE}" >&2
+  echo "${COLOR_FAIL}Traceback (most recent call last):${COLOR_NONE}" >&4
   for ((i=0;; i++)); do
-    read line fun file < <(caller $i)
+    read -r line fun file < <(caller $i)
     if [ "$line" ]; then
-      echo "${COLOR_FAIL} File '$file', line $line, in $fun${COLOR_NONE}" >&2
+      echo "${COLOR_FAIL} File '$file', line $line, in $fun${COLOR_NONE}" >&4
     else
       break
     fi
@@ -2323,6 +2441,135 @@ os::release::ubuntu () {
   echo "$release"
 }
 #! /bin/bash
+# mod: tmp
+# api: blib
+# txt: The `tmp` module provides functions to create and destroy temporary
+#      directories. Even if you don't remove the temporary file or directoy
+#      explicitely, the directory or file will be deleted when program
+#      exits.
+# env: TMPDIR: a subdirectory into /tmp to use to create temporary files or
+#      directories.
+# env: BLIB_TMPDIR: a full path to temporary directory to use to store files
+#      or other directories.
+# use: tmp::create
+#      # do some actions in current directory, which is temporary one
+#      tmp::destroy
+# use: echo $(tmp::file)
+
+BLIB_TMPDIR="/tmp/${TMPDIR:-blib}"
+
+__current_tmp=
+# fun: tmp::create <dirname>
+# api: blib
+# txt: create temporary directory and move working directory into it
+tmp::create () {
+  __current_tmp="$PWD"
+  mkdir -p "${BLIB_TMPDIR}/$1" && cd "${BLIB_TMPDIR}/$1"
+  std::add_quit_handler tmp tmp::destroy
+}
+
+# fun: tmp::exit
+# api: blib
+# txt: exit the temporary directory, but not remove it.
+tmp::exit () {
+  cd "${__current_tmp:-/}"
+}
+
+# fun: tmp::destroy
+# api: blib
+# txt: move to root directoy and remove temporary directory
+tmp::destroy () {
+  tmp::exit && rm -rf "${BLIB_TMPDIR}/$1" && unset __current_tmp
+}
+
+# fun: tmp::exists <name>
+# api: blib
+# txt: return true if the specified file name or directory name is
+#      a temporary file or directory.
+tmp::exists () {
+  [ -e "${BLIB_TMPDIR}/$1" ]
+}
+
+# fun: tmp::file
+# api: blib
+# txt: print to stdout the name of unique temporary file.
+tmp::file () {
+  mkdir -p "${BLIB_TMPDIR}" && echo ${BLIB_TMPDIR}/$$-${RANDOM}
+  std::add_quit_handler tmp tmp::destroy
+}
+
+# fun: tmp::touch <name>
+# api: blib
+# txt: create a temporary file with specified name in temporary directory.
+tmp::touch () {
+  mkdir -p "${BLIB_TMPDIR}" && : > "${BLIB_TMPDIR}/$1"
+}
+#! /bin/bash
+# mod: term
+# api: blib
+# txt: The `term` module provides functions related with terminal
+#      configuration. This module also define some useful color variables to
+#      be used in `out` module.
+
+# fun: term::attached
+# api: blib
+# txt: return true if output is a terminal, false otherwise
+term::attached () { [ -t 1 ] && ! ${BLIB_DISABLE_COLORS:-false}; }
+
+# fun: term::tcap <capability>
+# api: blib
+# txt: check if some capabilty is enabled in terminal
+term::tcap () { tput "$1" 2>/dev/null; }
+
+# fun: term::init
+# api: blib
+# txt: initialize terminal, in theory you never need to call this function,
+#      unless you want to change your terminal online.
+term::init () {
+  if term::attached; then
+    case "$(term::tcap colors)" in
+      256)
+        COLOR_NONE=$'\033[0;0;0m'
+        COLOR_INFO=$'\033[38;5;79m'
+        COLOR_WARN=$'\033[38;5;190m'
+        COLOR_FAIL=$'\033[38;5;160m'
+        COLOR_DATE=$'\033[38;5;242m'
+        COLOR_USER=$'\033[38;5;201m'
+        COLOR_BOLD=$'\033[1;15m'
+        ;;
+    esac
+  else
+    unset COLOR_NONE COLOR_INFO COLOR_WARN COLOR_FAIL
+    unset COLOR_DATE COLOR_USER COLOR_BOLD
+  fi
+}
+
+term::init
+#! /bin/bash
+# mod: version
+# api: blib
+# txt: The `version` module provides a number of functions to handle version
+#      numbers.
+
+# fun: version::cmp <version1> <version2>
+# txt: compare two version numbers, return -1 (255) if version1 is greater
+#      than version2, return 1 if version2 is greater than version1 and 0
+#      if both are equal
+version::cmp () {
+  local ver1 rev1 pat1 ver2 rev2 pat2
+  { IFS='.' read -r ver1 rev1 pat1 <<<"$1"; }
+  { IFS='.' read -r ver2 rev2 pat2 <<<"$2"; }
+
+  [[ "$ver1" -gt "$ver2" ]] && return 255
+  [[ "$ver2" -gt "$ver1" ]] && return 1
+  [[ "$rev1" -gt "$rev2" ]] && return 255
+  [[ "$rev2" -gt "$rev1" ]] && return 1
+  [[ "$pat1" -gt "$pat2" ]] && return 255
+  [[ "$pat2" -gt "$pat1" ]] && return 1
+
+  return 0
+}
+#! /bin/bash
 # mod: out
 # api: blib
 # txt: The `out` module provides functions to output messages in stderr or
@@ -2359,7 +2606,7 @@ out::info () { out::log "$1" "${COLOR_INFO}info${COLOR_NONE}"; }
 # env: COLOR_FAIL: defines the color to be used in this kind of messages.
 #      E: if set exit program with error code defined in the variable
 out::fail () {
-  out::log "$1" "${COLOR_FAIL}fail${COLOR_NONE}" >&2;
+  out::log "$1" "${COLOR_FAIL}fail${COLOR_NONE}" >&4;
   ${E:+exit $E}
 }
 
@@ -2367,13 +2614,30 @@ out::fail () {
 # txt: print an informational message in stdout.
 # txt: print a warning message in stderr.
 # env: COLOR_WARN: defines the color to be used in this kind of messages.
-out::warn () { out::log "$1" "${COLOR_WARN}warn${COLOR_NONE}" >&2; }
+out::warn () { out::log "$1" "${COLOR_WARN}warn${COLOR_NONE}" >&4; }
 
 # fun: out::user <message>
 # txt: print an informational message in stdout.
 # txt: print a user defined message in stdout
 # env: COLOR_USER: defines the color to be used in this kind of messages.
 out::user () { out::log "$1" "${COLOR_USER}user${COLOR_NONE}"; }
+
+# This code catch all messages in stderr and prefixed with out::fail,
+# cloning &2 to &4 and redirecting all &2 messages to &4
+
+if ${DEBUG:-false}; then
+  exec 4>&2
+else
+  exec 4>&2
+  coproc err_handler ( read -r line; out::fail "$line";)
+  export OUT__STDERR__PID="$!"
+  eval "exec 2>&${err_handler[1]}"
+fi
+
+out::_close_fd ()
+{
+  kill "${OUT__STDERR__PID}"
+}
 #! /bin/bash
 # mod: std
 # api: blib
@@ -2400,6 +2664,7 @@ std::quit () {
 #      std::add_quit_handler somefunc
 declare -A std__quit_handler
 std__quit_handler["tmp"]="tmp::destroy"
+std__quit_handler["out"]="out::_close_fd"
 std::add_quit_handler () {
   std__quit_handler["$1"]="$2"
 }
@@ -2572,136 +2837,7 @@ std::str2array () {
   str2array_ret=( "$@" )
 }
 declare -xa str2array_ret
-#! /bin/bash
-# mod: tmp
-# api: blib
-# txt: The `tmp` module provides functions to create and destroy temporary
-#      directories. Even if you don't remove the temporary file or directoy
-#      explicitely, the directory or file will be deleted when program
-#      exits.
-# env: TMPDIR: a subdirectory into /tmp to use to create temporary files or
-#      directories.
-# env: BLIB_TMPDIR: a full path to temporary directory to use to store files
-#      or other directories.
-# use: tmp::create
-#      # do some actions in current directory, which is temporary one
-#      tmp::destroy
-# use: echo $(tmp::file)
-
-BLIB_TMPDIR="/tmp/${TMPDIR:-blib}"
-
-__current_tmp=
-# fun: tmp::create <dirname>
-# api: blib
-# txt: create temporary directory and move working directory into it
-tmp::create () {
-  __current_tmp="$PWD"
-  mkdir -p "${BLIB_TMPDIR}/$1" && cd "${BLIB_TMPDIR}/$1"
-  std::add_quit_handler tmp tmp::destroy
-}
-
-# fun: tmp::exit
-# api: blib
-# txt: exit the temporary directory, but not remove it.
-tmp::exit () {
-  cd "${__current_tmp:-/}"
-}
-
-# fun: tmp::destroy
-# api: blib
-# txt: move to root directoy and remove temporary directory
-tmp::destroy () {
-  tmp::exit && rm -rf "${BLIB_TMPDIR}/$1" && unset __current_tmp
-}
-
-# fun: tmp::exists <name>
-# api: blib
-# txt: return true if the specified file name or directory name is
-#      a temporary file or directory.
-tmp::exists () {
-  [ -e "${BLIB_TMPDIR}/$1" ]
-}
-
-# fun: tmp::file
-# api: blib
-# txt: print to stdout the name of unique temporary file.
-tmp::file () {
-  mkdir -p "${BLIB_TMPDIR}" && echo ${BLIB_TMPDIR}/$$-${RANDOM}
-  std::add_quit_handler tmp tmp::destroy
-}
-
-# fun: tmp::touch <name>
-# api: blib
-# txt: create a temporary file with specified name in temporary directory.
-tmp::touch () {
-  mkdir -p "${BLIB_TMPDIR}" && : > "${BLIB_TMPDIR}/$1"
-}
-#! /bin/bash
-# mod: term
-# api: blib
-# txt: The `term` module provides functions related with terminal
-#      configuration. This module also define some useful color variables to
-#      be used in `out` module.
-
-# fun: term::attached
-# api: blib
-# txt: return true if output is a terminal, false otherwise
-term::attached () { [ -t 1 ] && ! ${BLIB_DISABLE_COLORS:-false}; }
-
-# fun: term::tcap <capability>
-# api: blib
-# txt: check if some capabilty is enabled in terminal
-term::tcap () { tput "$1" 2>/dev/null; }
-
-# fun: term::init
-# api: blib
-# txt: initialize terminal, in theory you never need to call this function,
-#      unless you want to change your terminal online.
-term::init () {
-  if term::attached; then
-    case "$(term::tcap colors)" in
-      256)
-        COLOR_NONE=$'\033[0;0;0m'
-        COLOR_INFO=$'\033[38;5;79m'
-        COLOR_WARN=$'\033[38;5;190m'
-        COLOR_FAIL=$'\033[38;5;160m'
-        COLOR_DATE=$'\033[38;5;242m'
-        COLOR_USER=$'\033[38;5;201m'
-        COLOR_BOLD=$'\033[1;15m'
-        ;;
-    esac
-  else
-    unset COLOR_NONE COLOR_INFO COLOR_WARN COLOR_FAIL
-    unset COLOR_DATE COLOR_USER COLOR_BOLD
-  fi
-}
-
-term::init
-#! /bin/bash
-# mod: version
-# api: blib
-# txt: The `version` module provides a number of functions to handle version
-#      numbers.
-
-# fun: version::cmp <version1> <version2>
-# txt: compare two version numbers, return -1 (255) if version1 is greater
-#      than version2, return 1 if version2 is greater than version1 and 0
-#      if both are equal
-version::cmp () {
-  local ver1 rev1 pat1 ver2 rev2 pat2
-  { IFS='.' read -r ver1 rev1 pat1 <<<"$1"; }
-  { IFS='.' read -r ver2 rev2 pat2 <<<"$2"; }
-
-  [[ "$ver1" -gt "$ver2" ]] && return 255
-  [[ "$ver2" -gt "$ver1" ]] && return 1
-  [[ "$rev1" -gt "$rev2" ]] && return 255
-  [[ "$rev2" -gt "$rev1" ]] && return 1
-  [[ "$pat1" -gt "$pat2" ]] && return 255
-  [[ "$pat2" -gt "$pat1" ]] && return 1
-
-  return 0
-}
-BLIB_VERSION='1.1'
+BLIB_VERSION='1.2'
 #! /bin/bash
 # mod: main
 # txt: The ``main`` module contain the specified potion body.
@@ -2746,8 +2882,6 @@ main::init () {
   out::user "detected hardware architecture: $(std::arch)"
   out::user "detected os family: $(os::family)"
   out::user "detected os provider: $(os::provider)"
-
-
 }
 
 # general options handlers
@@ -2838,6 +2972,15 @@ main::run () {
   context::run
 }
 
+# eval action
+main::eval ()
+{
+  local cmd="$1"; shift
+  main::init "in-line"
+  meta::populate
+  "$cmd" "$@" || err::trace
+}
+
 # fun: main [arguments]
 # txt: function to create random errors and weird behaviour.
 main () {
@@ -2853,7 +2996,7 @@ main () {
   arg::opt MAIN -C --no-color main::opt_nocolor 'do not output colors ever'
 
   arg::action create main::create 'create new potion from templates'
-  arg::param create "infredients+" \
+  arg::param create "ingredients+" \
     'URL to the ingredient files to make the potion'
   arg::opt create -o: --output: main::create::opt_output \
     'set path to output potion filename'
@@ -2872,50 +3015,15 @@ main () {
   arg::opt run -s:  --secrets:   main::run::opt_secrets \
     'set a secret file or URL to store passwords'
 
+  arg::action eval main::eval 'run potion command'
+  arg::param eval "command" \
+    'the potion command to evaluate'
+  arg::param eval "params*" \
+    'parameters to pass to the evaluation command'
+
   arg::parse "$@"
 }
 shopt -s expand_aliases
-#! /bin/bash
-# mod: deprecate
-# txt: This internal module provides a way to mark deprecated features or
-#      modules.
-
-# fun: deprecate [name=]<name> [version=version] [date=date]
-# txt: set a deprecation mark called name (could be a message), when potion
-#      version is lower to specified version a warning is raised, otherwise
-#      execution fails with an error. The same behaviour can be used with
-#      a date in the format %y-%m-%d, until that date the deprecation
-#      warning message will show, after that date execution breaks.
-deprecate () {
-  local version date name
-  eval "$(std::parse "$@")"
-
-  # shellcheck disable=SC2153
-  version::cmp "$VERSION" "$version"
-  case $? in
-    0|255)
-      err::trace "DEPRECATION ERROR: $name";;
-    1)
-      local line fun file; read -r line fun file < <(caller)
-      out::warn $"DEPRECATION WARNING [$fun at $file:$line]: $name"
-  esac
-
-  [[ "$date" ]] || return
-
-  local year month day
-
-  { IFS='-' read -r year month day <<< "$date"; }
-
-  if [[ "$year" -lt "$(printf "%(%Y)T" -1)" ]] &&
-    [[ "$month" -lt "$(printf "%(%m)T" -1)" ]] &&
-    [[ "$day" -lt "$(printf "%(%d)T" -1)" ]]
-  then
-      local line fun file; read -r line fun file < <(caller)
-      out::warn $"DEPRECATION WARNING [$fun at $file:$line]: $name"
-  else
-    err::trace "DEPRECATION ERROR: $name"
-  fi
-}
 std::installed 'grep' ||  err::trace 'grep is required but not found'
 std::installed 'egrep' ||  err::trace 'egrep is required but not found'
 std::installed 'uname' ||  err::trace 'uname is required but not found'
diff --git a/src/secret b/src/secret
--- a/src/secret
+++ b/src/secret
@@ -6,28 +6,91 @@
 # env: SECRET_MASTERKEY: Path to file where the master key for secrets lives.
 #      By default ``/etc/potion.key``
 
-SECRET_MASTERKEY=/etc/potion.key
+SECRET_MASTERKEY="${SECRET_MASTERKEY:-/etc/potion.key}"
 
 declare -A _secrets
 
-# fun: secret::load [name=]<name>
-# txt: load a secret file
-secret::load () {
+# fun: secret::dump [name=]<name>
+# txt: dump the encrypted file of a secret plain file.
+secret::dump ()
+{
+  _gpg () {
+    gpg --symmetric -z 9 --require-secmem \
+        --cipher-algo AES256 --s2k-cipher-algo AES256 \
+        --s2k-digest-algo SHA512 --s2k-mode 3 --batch \
+        --s2k-count 65000000 --compress-algo BZIP2 --armor \
+        --passphrase-file "${SECRET_MASTERKEY}"
+  }
+
   local url="${1#name=}"
   case "$url" in
     gpg://*|gpg+file://*)
       url="${url#*://}"
-      eval "$(gpg -d "$url")";;
+      _gpg < "$url";;
     gpg+*)
       url="${url#gpg+}"
-      eval "$(curl -sqL "$url" | gpg -d)";;
+      curl -sqL "$url" | _gpg;;
+    crypt+*)
+      url="${url#crypt+}"
+      curl -sqL "$url" |
+              openssl enc -e -a -aes-256-cbc -kfile "${SECRET_MASTERKEY}";;
+    *) url="${url#file://}"
+       # shellcheck disable=SC1090
+       cat "$url" || err::trace "Invalid secret file format" ;;
+  esac
+}
+
+# fun: secret::load [name=]<name>
+# txt: load a secret file
+secret::load () {
+  local err=$"Unable to load secrets"
+  local url="${1#name=}"
+  case "$url" in
+    gpg://*|gpg+file://*)
+      url="${url#*://}"
+      eval "$(gpg -d --batch --passphrase-file "$SECRET_MASTERKEY" "$url")" ||
+        err::trace "$err"
+      ;;
+    gpg+*)
+      url="${url#gpg+}"
+      eval "$(curl -sqL "$url" |
+              gpg -d --batch --passphrase-file "$SECRET_MASTERKEY")" ||
+                err::trace "$err"
+      ;;
     crypt+*)
       url="${url#crypt+}"
       eval "$(curl -sqL "$url" |
-              openssl enc -d -a -aes256 -kfile "${SECRET_MASTERKEY}")";;
+              openssl enc -d -a -aes-256-cbc -kfile "${SECRET_MASTERKEY}")" ||
+        err::trace "$err"
+      ;;
     *) url="${url#file://}"
        # shellcheck disable=SC1090
-       source "$url" || err::trace "Invalid secret file format" ;;
+       source "$url" || err::trace "$err" ;;
+  esac
+}
+
+# fun: secret::load_inline <format> <content>
+# txt: load scripts from the inline string. Available formats are plain,
+#      crypt or gpg.
+secret::load_inline () {
+  local err=$"Unable to load secrets inline"
+  local format="${1#name=}"
+  case "$format" in
+    gpg)
+      eval "$(gpg --batch --passphrase-file "${SECRET_MASTERKEY}" -d <<<"$2")" ||
+        err::trace "$err"
+      ;;
+    crypt)
+      eval "$(openssl enc -d -a -aes-256-cbc -kfile "${SECRET_MASTERKEY}" <<<"$2")" ||
+        err::trace "$err"
+      ;;
+    plain)
+      eval "$2" || err::trace "$err"
+      ;;
+    *)
+      # shellcheck disable=SC1090
+      source "$url" || err::trace "$err"
+      ;;
   esac
 }
 
