Release v0.2.3

diff --git a/src/artifact b/src/artifact
--- a/src/artifact
+++ b/src/artifact
@@ -17,16 +17,10 @@ artifact::hmac () {
   fi
 }
 
-# fun: artifact::enable
-# txt: return true if artifact support is enabled.
-artifact::enable () {
-  [ "$POTION_ARTIFACTS" ]
-}
-
 # fun: artifact::extract
-# txt: extract artifacts if enabled
+# txt: extract artifacts if artifact support is enabled.
 artifact::extract () {
-  artifact::enable || return 0
+  [ "$POTION_ARTIFACTS" ] || return 0
   [ -e "${POTION_TMPDIR}/.artifacts" ] && return 0
 
   tmp::create
@@ -42,17 +36,32 @@ artifact::exists () {
   artifact::extract
   [ -r "${POTION_TMPDIR}/_artifacts/$1" ]
 }
+
 # fun: artifact::read <artifact_name>
-# txt: read and eval specific artifact from potion.
+# txt: read a specific artifact from potion.
 artifact::read () {
-  artifact::extract
   artifact::exists "$1" ||
     err::trace "Missing artifact: '$1'"
 
-  if ${ARTIFACT_EVAL:-false}; then
-    local content="$(< ${POTION_TMPDIR}/_artifacts/$1)"
-    eval echo -n \""${content}"\"
-  else
-    cat "${POTION_TMPDIR}/_artifacts/$1"
-  fi
+  cat "${POTION_TMPDIR}/_artifacts/$1"
+}
+
+
+# fun: artifact::read <artifact_name>
+# txt: read a specific artifact from potion.
+artifact::eval () {
+  artifact::exists "$1" ||
+    err::trace "Missing artifact: '$1'"
+
+  local content="$(< ${POTION_TMPDIR}/_artifacts/$1)"
+  eval echo -n \""${content//\"/\\\"}"\"
+}
+
+# fun: artifacts::build <directory>
+# txt: scan the directory passed as argument and return a POTION_ARTIFACTS
+#      variable to stdout with the encoded version of the artifacts.
+artifact::build () {
+  local artifacts="$(cd "$1" && tar -c . | base64 -w0)"
+  echo "POTION_ARTIFACTS='${artifacts}'"
+  echo
 }
diff --git a/src/context b/src/context
--- a/src/context
+++ b/src/context
@@ -5,12 +5,56 @@
 
 alias context=function
 
+declare -A __context__task
+# fun: context::task::enqueue <fun>
+# txt: enqueue a task to be done when context finished.
+context::task::enqueue () {
+  if ! std::strin "${__context__task["${CONTEXT}"]}" ",$1,"; then
+    __context__task["${CONTEXT}"]+=",$1,"
+  fi
+}
+
+# fun: context::task::apply <context>
+# txt: apply functions enqueued by context::task::enqueue.
+context::task::apply () {
+  task="${__context__task["${1}"]}"
+  if [ "$task" ]; then
+    export IFS=,
+    for t in $task; do
+      [ "$t" ] || continue
+      eval "${t}" || err::trace "Unable to apply post-context task: $t ($CONTEXT)"
+    done
+  fi
+}
+
+# fun: context::execute <name>
+# txt: Execute a context named as name.
+# var: CONTEXT contains the context name, and this variable will be
+#      propagated to other functions in the same context.
+context::execute () {
+  export CONTEXT="$1" && $1 && context::task::apply "$1"
+}
+
 # fun: context::run
 # txt: run all context in paralell.
 context::run () {
+  local tim="$(std::timestamp)"
+  local count=0
+  local cctx=0
+  [ "$POTION_COMPILED" ] && local kind="compiled" || local kind="in-line"
   while read d f context; do
-    out::info "found context: $context"
-    $context &
+    ((cctx++))
+  done < <(declare -F | grep '^declare -f @')
+  out::user "found ${cctx} contexts"
+  ${PRETEND:-false} &&
+    out::info "Starting $kind potion execution (pretending)" ||
+    out::info "Starting $kind potion execution"
+  while read d f context; do
+    context::execute $context &
+    ${ONETHREAD:-false} && wait
   done < <(declare -F | grep '^declare -f @')
   wait
+  context::task::apply "main"
+  tim="$(( $(std::timestamp) - $tim ))"
+  out::info "Finished potion exection in ${tim} seconds."
 }
diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -2,7 +2,8 @@
 # mod: main
 # txt: The ``main`` module contain the specified potion body.
 
-VERSION="0.1"
+VERSION="0.2.3"
+CONTEXT="main"
 
 # fun: main::init
 # txt: print nice potion logo and some custom messages at the beginning.
@@ -30,22 +31,24 @@ main::init () {
   out::user "detected hardware architecture: $(std::arch)"
   out::user "detected os family: $(os::family)"
   out::user "detected os provider: $(os::provider)"
-  out::info "starting potion"
 }
 
 # general options handlers
-main::opt_debug () { set -x; return 1; }
-main::opt_version () { out::info "Potion $VERSION"; exit 0; }
+main::opt_debug () { set -x; return 1;}
+main::opt_version () { out::info "Potion $VERSION"; exit 0;}
 main::opt_quiet () { QUIET=true; return 1;}
+main::opt_pretend () { PRETEND=true; return 1;}
+main::opt_verbose () { VERBOSE=true; return 1;}
 
 # create action
-main::create::opt_artifacts () { main__create__artifacts="$1"; return 2; }
-main::create::opt_compress () { main__create__compress=true; return 1; }
+main::create::opt_artifacts () { main__create__artifacts="$1"; return 2;}
+main::create::opt_compress () { main__create__compress=true; return 1;}
 main::create::opt_output () { main__create__output="$1"; return 2;}
+main::create::opt_secrets () { main__create__secrets="$1"; return 2;}
 
 main::create () {
   local output=$'#! /bin/bash\nPOTION_COMPILED=true\n'
-  main::init
+  ${QUIET:-false} || main::init
   out::info "output file: ${main__create__output:=./a.potion}"
   output+="$(<$0)"$'\n'
   if [ "${main__create__artifacts}" ]; then
@@ -57,9 +60,13 @@ main::create () {
 
     artifacts="$(cd ${main__create__artifacts} &&
                  tar -c . | base64)"
-    output+=$'\n'"POTION_ARTIFACTS='${artifacts}'"$'\n'
+    output+=$'\n'"$(artifact::build "${main__create__artifacts}")"$'\n'
 
-    out::info "dumped artifacts from: ${main__create__artifacts}"
+    out::user "dumped artifacts from: ${main__create__artifacts}"
+  fi
+  if [ "${main__create__secrets}" ]; then
+    output+=$'\n'"secret::load '${main__create__secrets}'"$'\n'
+    out::user "set secret url to: ${main__create__secrets}"
   fi
   out::info "created core launcher"
   for template in "$@"; do
@@ -79,19 +86,39 @@ main::create () {
   echo "${output}" > "${main__create__output}"
 }
 
-main::run_compiled () {
-  main::init
-  out::info "running compiled potion"
+# run action
+main::run::opt_artifacts () { main__run__artifacts="$1"; return 2; }
+main::run::opt_secrets () { main__run__secrets="$1"; return 2; }
+main::run () {
+  main::init "in-line"
+  if [ "${main__run__artifacts}" ]; then
+    [ -d "${main__run__artifacts}" ] ||
+      err::trace "Artifacts directory does not exists or isn't a directory"
+
+    [ -r "${main__run__artifacts}" ] ||
+      err::trace "Unable to read artifacts directory"
+
+    eval $(artifact::build "${main__run__artifacts}")
+    out::user "dumped artifacts from: ${main__run__artifacts}"
+  fi
+  if [ "${main__run__secrets}" ]; then
+    secret::load "${main__run__secrets}"
+    out::user "loaded secrets from: ${main__run__secrets}"
+  fi
+  source "$@" || err::trace "Unable to load potion file(s): $@"
+  context::run
 }
 
 # fun: main [arguments]
 # txt: function to create random errors and weird behaviour.
 main () {
   # if this is a compiled potion, we don't need main
-  ${POTION_COMPILED:-false} && main::run_compiled "$@" && return 0
+  ${POTION_COMPILED:-false} && main::init && return 0
   
   arg::opt MAIN -q --quiet   main::opt_quiet   'do not output messages'
+  arg::opt MAIN -v --verbose main::opt_verbose 'enable verbose mode'
   arg::opt MAIN -d --debug   main::opt_debug   'enable debug mode'
+  arg::opt MAIN -p --pretend main::opt_pretend 'do nothing, just pretending'
   arg::opt MAIN -V --version main::opt_version 'show program version number'
 
   arg::action create main::create 'create new potion from templates'
@@ -103,6 +130,16 @@ main () {
     'set path to artifacts directory'
   arg::opt create -c  --compress   main::create::opt_compress \
     'create compressed potion (require gzip)'
+  arg::opt create -s:  --secrets:   main::create::opt_secrets \
+    'set a secret file or URL to store passwords'
+  
+  arg::action run main::run 'run potion template'
+  arg::param run "infredients+" \
+    'path to the ingredient files to make the potion'
+  arg::opt run -a: --artifacts: main::run::opt_artifacts \
+    'set path to artifacts directory'
+  arg::opt run -s:  --secrets:   main::run::opt_secrets \
+    'set a secret file or URL to store passwords'
 
   arg::parse "$@"
 }
diff --git a/src/std b/src/std
--- a/src/std
+++ b/src/std
@@ -55,7 +55,7 @@ std::strin () {
 # txt: sleep for specified number of seconds. This function is pure-bash, so
 #      not need sleep(1) command.
 std::sleep () {
-  read -t "$1"
+  read -N 0 -t "$1" -s -r </dev/tty 3<&- 3<&0 <&3
 }
 
 # fun: std::func <func_name>
@@ -96,3 +96,50 @@ std::os::provider () {
 
 declare -A std__os__provider
 std__os__provider["/etc/arch-release"]="archlinux"
+
+# fun: std::timestamp
+# txt: return the UNIX timestamp
+std::timestamp () {
+  date +%s
+}
+
+# fun: std::parse <arg string>
+# txt: parse an argument string in the form key=value and promote this
+#      variables to environment.
+std::parse () {
+  local hasname=false
+  local fst="$1"; shift
+
+  [ "${fst#name=}" != "${fst}" ] || fst="name=$fst"
+
+  for arg in "$fst" "$@"; do
+    std::strin "$arg" "=" || err::trace "Invalid argument: $arg"
+    [ "${arg#name=}" != "${arg}" ] && hasname=true
+    echo -n "local ${arg/=/=\'}';"
+  done
+  ${hasname} || err::trace "The parameter 'name' is mandatory"
+  shift
+  echo
+}
+
+# fun: std::run <command>
+# txt: Run command passed as argument if $PRETEND is not set to true
+# env: PRETEND: if true do nothing.
+std::run () {
+  ${PRETEND:-false} || "$@"
+}
+
+# fun: std::installed <command>
+# txt: return true if command is installed in path
+std::installed () {
+  std::mute type -p "$1"
+}
+
+# fun: std::is_dir_empty <dir>
+# txt: return true if dir is empty
+std::is_dir_empty () {
+  for f in $1/*; do
+    [ "$f" == "$1/*" ] && return 0
+    return 1
+  done
+}
